Review
freepaddler/yap-s56-loyalty pull request #2
Opened 2023-08-26 03:23 UTC by freepaddler

2023-08-27 16:08 UTC, valentinsoe requested changes
Спасибо за работу.
Отлично что в ней есть тесты, что предусмотрен парсинг retry-after заголовка и асинхронные запросы во внешний сервис.

Что хотелось бы улучшить - разделение кода на модули по зонам ответственности. То есть иметь уровень хендлеров, которые работают только с http и сериализацией/десериализацией запросов. Уровень БД(он уже есть). И уровень бизнес-логики, в котором все валидации/условия достаточности балансов и т.д.

Еще хотелось бы отметить работу с многопоточностью.
Много где дождавшись завершения контекста, мы этот же констекст пытаемся отменить, что немного бессмысленно.
И очередь на отправку, которая потенциально может бесконечно расти мне не очень нравится. Да, она амортизирует собой буфферы каналов, но ничто не запрещает ей очень сильно расти.

2023-08-27 16:08 UTC, valentinsoe commented on pkg/luhna/luhna.go
> +func Generate(prefix string, l int) (s string) {
Генерировать номера заказов у нас необходимости нет. Можно либо подключить пакет как внешний, либо удалить лишнее.

2023-08-27 16:17 UTC, valentinsoe commented
И то ли я схожу с ума, а тесты проходят, то ли что-то не так:)
Я не вижу того куска кода, который при получении успешного статуса обновлял бы баланс пользователя.

2023-09-01 14:50 UTC, freepaddler commented on pkg/luhna/luhna.go
> +func Generate(prefix string, l int) (s string) {
сделала внешним

2023-09-14 10:42 UTC, merged